global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python-server'
    static_configs:
      - targets: ['python-server:8000']
      
  - job_name: 'consistency-validator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['consistency-validator:8080']