version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-logs_db}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  mongodb_logs: 